name: Java CI
on: 
  push:
    branches:
      - main
      - 'releases-**'
  pull_request:
    branches:
      - main
      - 'releases-**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true
#      - run: mkdir staging && cp target/*.jar staging
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Package
#          path: staging